#!/usr/bin/env bash
# This script installs nginx web server on a server
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw status
sudo service nginx status
curl http://35.180.228.223:80
