#!/usr/bin/env bash
# This script installs nginx web server on a server
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
if [ curl localhost | echo "Hello World" ]; then
    exit 0
else
    exit 1
fi
sudo service nginx restart
