#!/usr/bin/env bash
# clock that displays the time for 12 hours and 59 minutes
i=0 n=1
while [[ $i -le 12 ]]
do
       echo "Hour: $i"
       
       while [[ $n -le 59 ]]
       	do 
		echo "$n"
		((n++))
	done
	((i++))
	((n=1))	
done
