#!/usr/bin/env bash
# Block all incoming traffic but
# 80 (HTTP)
# 443 (HTTPS)
# 22 (SSH)
# 8080 (HTTP) forwarded to port 80 (HTTP)
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw allow 8080/tcp
sudo apt-get install -y iptables
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
sudo apt-get install -y iptables-persistent
sudo ufw enable
